### ISSUE TITLE
Missing CLA bot for PRs

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-code#26]
### Describe the issue

When I submitted #25 the CLA bot wasn't in the [list of checks](https://github.com/Pirate-Weather/pirate-weather-code/pull/25/checks) or commented on the PR to say that the agreement needed to be signed.

The bot is still running on the Translations and the Weather Vue repo and should be removed. Not an urgent issue but something that should be addressed before people submit their own PRs. @

### Acknowledgements

- [X] This issue is related to the self-hosting code and not an API issue.
- [X] I have read through the [README](https://github.com/Pirate-Weather/pirate-weather-code/blob/main/README.md) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I guess for some reason it didn't popup for my first PR for some reason. Has it been disabled on the other repos?

**Comment by alexander0042** [comment]
Ok, I think I've fixed this now! It's been removed from those other two repos for sure, and should be working here with approvals for github actions and dependabot
